language: python
before_install:
- export PATH="$HOME/pandoc:$PATH"
- mkdir $HOME/pandoc
- curl -O https://s3.amazonaws.com/rstudio-buildtools/pandoc-1.12.3.zip
- unzip -j pandoc-1.12.3.zip pandoc-1.12.3/linux/debian/x86_64/pandoc -d $HOME/pandoc
- chmod +x $HOME/pandoc/pandoc
- pandoc --version
- rm pandoc-1.12.3.zip
python:
- '2.7'
install:
- pip install -r requirements.txt
script: nikola build
after_success: 
    # Get to the Travis build directory, configure git and clone the repo
    - cd $HOME
    - git config --global user.email ${GH_EMAIL}
    - git config --global user.name ${GH_NAME}
    # Commit and Push the Changes
    - git clone --quiet --branch=gh-pages https://${GH_TOKEN}@github.com/johnfoster-pge-utexas/PGE334-ResGeomechanics gh-pages > /dev/null
    - cd gh-pages
    - cp -Rf $HOME/build/johnfoster-pge-utexas/PGE334-ResGeomechanics/output/* .
    - git add -A
    - git commit -m "Travis CI autocommit from travis build $TRAVIS_BUILD_NUMBER"
    - git push -fq origin gh-pages > /dev/null
    - git push -fq https://${GH_TOKEN}@github.com/johntfoster/PGE334-ResGeomechanics gh-pages
